export * from "./client";
export { authApi } from "./auth";
export type { LoginRequest, LoginResponse, RegisterRequest, MeResponse } from "./auth";
export { clientiApi } from "./clienti";
export type { ClientCreate, ClientUpdate, ClientVehicolCreate, ClientiQuery } from "./clienti";
export { companiesApi } from "./companies";
export type { Company, CompanyCreate, CompanyUpdate, AnafCompany } from "./companies";
export { departmentsApi } from "./departments";
export type { Department, DepartmentCreate, DepartmentUpdate } from "./departments";
export { employeesApi } from "./employees";
export type { Employee, EmployeeCreate, EmployeeUpdate, EmployeesQuery } from "./employees";
export { disclaimersApi } from "./disclaimers";
export type { Disclaimer, DisclaimerCreate, DisclaimerUpdate } from "./disclaimers";
export { registersApi } from "./registers";
export type { Register, RegisterCreate, RegisterUpdate } from "./registers";
export { locationsApi } from "./locations";
export type { LocationDetail, LocationCreate, LocationUpdate } from "./locations";
export { categoriesApi, itemsApi } from "./catalog";
export type { Category, CategoryCreate, CategoryUpdate, Item, ItemCreate, ItemUpdate, ItemType } from "./catalog";
export { subscriptionApi } from "./subscription";
export { efacturaApi } from "./efactura";
