"""add_timestamps_and_receipt_pay_method

Revision ID: 4508c5691bc2
Revises: 7434440074ab
Create Date: 2026-03-20 21:54:01.676026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4508c5691bc2'
down_revision: Union[str, None] = '7434440074ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default='1970-01-01 00:00:00'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pay_method', sa.Enum('NEPLATIT', 'CARD', 'CASH', 'OP', 'PARTIAL', name='pay_method'), nullable=False, server_default='NEPLATIT'))
        batch_op.add_column(sa.Column('partial_pay', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default='1970-01-01 00:00:00'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('partial_pay')
        batch_op.drop_column('pay_method')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
