"""add image_path

Revision ID: 874fffb60087
Revises: cd40edc7cc5f
Create Date: 2026-03-20 20:44:43.418006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874fffb60087'
down_revision: Union[str, None] = 'cd40edc7cc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
