"""add_account_and_account_id_fk

Revision ID: ba800301f486
Revises: 874fffb60087
Create Date: 2026-03-20 20:53:56.536022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba800301f486'
down_revision: Union[str, None] = '874fffb60087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('username', name=op.f('uq_accounts_username'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_is_deleted_id', ['is_deleted', 'id'], unique=False)
        batch_op.create_index('ix_accounts_username', ['username'], unique=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key(batch_op.f('fk_categories_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key(batch_op.f('fk_items_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key(batch_op.f('fk_themes_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_themes_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_username')
        batch_op.drop_index('ix_accounts_is_deleted_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
