"""add_employee_id_to_receipt_items

Revision ID: ea4894924a46
Revises: 7fecc7ca7108
Create Date: 2026-03-21 01:02:08.201800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4894924a46'
down_revision: Union[str, None] = '7fecc7ca7108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_receipt_items_employee_id_employees'), 'employees', ['employee_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_receipt_items_employee_id_employees'), type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
